name: CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "README.md"
      - ".github/ISSUE_TEMPLATE/**"
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, pcntl, pdo, pdo_sqlite, sqlite3
      - uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-${{ runner.os }}-
      - run: composer validate --no-check-publish --strict
      - run: composer install --no-interaction --no-progress --prefer-dist --no-scripts --no-plugins
      - run: vendor/bin/pint --test

  static-analysis:
    name: static-analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, pcntl, pdo, pdo_sqlite, sqlite3
          ini-values: memory_limit=-1
      - uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-${{ runner.os }}-
      - run: composer validate --no-check-publish --strict
      - run: composer install --no-interaction --no-progress --prefer-dist --no-scripts --no-plugins
      - name: Cache PHPStan
        uses: actions/cache@v4
        with:
          path: .phpstan/cache
          key: phpstan-${{ runner.os }}-${{ hashFiles('phpstan.neon', 'phpstan.neon.dist') }}
          restore-keys: phpstan-${{ runner.os }}-
      - name: PHPStan (level 5 по-умолчанию)
        run: |
          if [ ! -f phpstan.neon ]; then
            echo "parameters:\n  level: 5\n  paths:\n    - app\n" > phpstan.neon
          fi
          vendor/bin/phpstan analyse --no-progress

  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      APP_ENV: testing
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, pcntl, pdo, pdo_sqlite, sqlite3
      - uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-${{ runner.os }}-
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: php artisan key:generate --no-interaction
      - run: php artisan migrate --no-interaction --force || echo "skip migrations (none yet)"
      - run: vendor/bin/phpunit --colors=always --log-junit junit.xml
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit
          path: junit.xml
